# Adapted from https://github.com/nf-core/demultiplex/blob/17cde5d8f22f5327beac9637e941e4775ada1b3f/.github/workflows/ci.yml
name: Run nf-test

on:
  push:
  pull_request:

env:
  NXF_VER: 24.04.1
  NXF_ANSI_LOG: false
  NFT_VER: "0.9.0"
  NFT_WORKDIR: "~"
  NFT_DIFF: "pdiff"
  NFT_DIFF_ARGS: "--line-numbers --expand-tabs=2"

jobs:
  test:
    name: Run nf-tests and pipeline
    runs-on: "ubuntu-24.04"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pdiff to see diff between nf-test snapshots
        run: |
          python -m pip install --upgrade pip
          pip install pdiff

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ env.NXF_VER }}"

      - uses: nf-core/setup-nf-test@v1
        with:
          version: ${{ env.NFT_VER }}

      - name: Run Tests
        run: |
          nf-test test --ci

      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test
